/*
 * ClientJFrame.java
 *
 * Created on 01 June 2003, 15:56
 */

package jfreerails.client.top;



/**
 *  The JFrame that you see while you are playing the game.
 * @author  Luke
 */
public class ClientJFrame extends javax.swing.JFrame {
    
    private GUIComponentFactory gUIComponentFactory;

    /** Creates new form ClientJFrame. */
    public ClientJFrame(GUIComponentFactory gcf) {
        setup(gcf);
    }
    
    private void setup(GUIComponentFactory gcf) {
        this.gUIComponentFactory=gcf;
        initComponents();       
        gUIComponentFactory.createDateJLabel();
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        rhsjPanel = new javax.swing.JPanel();
        mapOverview = gUIComponentFactory.createOverviewMap();
        trainsJTabPane1 = gUIComponentFactory.createTrainsJTabPane();

        lhsjPanel = new javax.swing.JPanel();
        mainMapView = gUIComponentFactory.createMainMap();
        statusjPanel = new javax.swing.JPanel();
        datejLabel = gUIComponentFactory.createDateJLabel();
        cashjLabel = gUIComponentFactory.createCashJLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        gameMenu = gUIComponentFactory.createGameMenu();
        buildMenu = gUIComponentFactory.createBuildMenu();
        displayMenu = gUIComponentFactory.createDisplayMenu();
        reportsMenu = gUIComponentFactory.createReportsMenu();
        helpMenu = gUIComponentFactory.createHelpMenu();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        rhsjPanel.setLayout(new java.awt.GridBagLayout());

        rhsjPanel.add(mapOverview, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        rhsjPanel.add(trainsJTabPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(rhsjPanel, gridBagConstraints);

        lhsjPanel.setLayout(new java.awt.GridBagLayout());

        mainMapView.setAlignmentX(0.0F);
        mainMapView.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        lhsjPanel.add(mainMapView, gridBagConstraints);

        statusjPanel.add(datejLabel);

        statusjPanel.add(cashjLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        lhsjPanel.add(statusjPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(lhsjPanel, gridBagConstraints);

        gameMenu.setText("Game");
        jMenuBar1.add(gameMenu);

        buildMenu.setText("Build");
        jMenuBar1.add(buildMenu);

        displayMenu.setText("Display");
        jMenuBar1.add(displayMenu);

        reportsMenu.setText("Reports");
        jMenuBar1.add(reportsMenu);

        helpMenu.setText("Help");
        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application. */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    public static void main(String args[]) {
        new ClientJFrame(new GUIComponentFactoryTestImpl()).setVisible(true);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JMenu buildMenu;
    javax.swing.JLabel cashjLabel;
    javax.swing.JLabel datejLabel;
    javax.swing.JMenu displayMenu;
    javax.swing.JMenu gameMenu;
    javax.swing.JMenu helpMenu;
    javax.swing.JMenuBar jMenuBar1;
    javax.swing.JPanel lhsjPanel;
    javax.swing.JScrollPane mainMapView;
    javax.swing.JPanel mapOverview;
    javax.swing.JMenu reportsMenu;
    javax.swing.JPanel rhsjPanel;
    javax.swing.JPanel statusjPanel;
    javax.swing.JTabbedPane trainsJTabPane1;
    // End of variables declaration//GEN-END:variables
    
}
