/*
 * ClientJFrame.java
 *
 * Created on 01 June 2003, 15:56
 */

package jfreerails.client.top;

/**
 *
 * @author  Luke
 */
public class ClientJFrame extends javax.swing.JFrame {
    
    private GUIComponentFactory gUIComponentFactory;
    
    /** Creates new form ClientJFrame */
    public ClientJFrame(GUIComponentFactory gcf) {
        this.gUIComponentFactory=gcf;
        initComponents();
        gUIComponentFactory.createDateJLabel();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        rhsjPanel = new javax.swing.JPanel();
        trainsJPanel = gUIComponentFactory.createTrainsJPanel();
        datejLabel = gUIComponentFactory.createDateJLabel();
        mapOverview = gUIComponentFactory.createOverviewMap();
        cashjLabel = gUIComponentFactory.createCashJLabel();
        mainMapView = gUIComponentFactory.createMainMap();
        messageJLabel = gUIComponentFactory.createMessagePanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        gameMenu = gUIComponentFactory.createGameMenu();
        buildMenu = gUIComponentFactory.createBuildMenu();
        displayMenu = gUIComponentFactory.createDisplayMenu();
        helpMenu = gUIComponentFactory.createHelpMenu();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        rhsjPanel.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        rhsjPanel.add(trainsJPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        rhsjPanel.add(datejLabel, gridBagConstraints);

        rhsjPanel.add(mapOverview, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        rhsjPanel.add(cashjLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        getContentPane().add(rhsjPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(mainMapView, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(messageJLabel, gridBagConstraints);

        gameMenu.setText("Game");
        jMenuBar1.add(gameMenu);

        buildMenu.setText("Build");
        jMenuBar1.add(buildMenu);

        displayMenu.setText("Display");
        jMenuBar1.add(displayMenu);

        helpMenu.setText("Help");
        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        //pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new ClientJFrame(new GUIComponentFactoryTestImpl()).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datejLabel;
    private javax.swing.JLabel cashjLabel;
    private javax.swing.JPanel trainsJPanel;
    private javax.swing.JMenu displayMenu;
    private javax.swing.JScrollPane mainMapView;
    private javax.swing.JMenu buildMenu;
    private javax.swing.JMenu gameMenu;
    private javax.swing.JPanel mapOverview;
    private javax.swing.JPanel rhsjPanel;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel messageJLabel;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
    
}
