/*
 * ConfirmExitJPanel.java
 *
 * Created on 20 January 2005, 15:56
 */

package freerails.client.view;

import freerails.client.renderer.RenderersRoot;
import freerails.controller.ModelRoot;

import javax.swing.*;

/**
 * JPanel that didplays confirmation of exiting, used when the exit menu item is
 * selected or x is pressed.
 *
 * @author SonnyZ
 */
public class ConfirmExitJPanel extends javax.swing.JPanel implements View {

    private static final long serialVersionUID = 3256728398394110517L;

    /**
     * Creates new form ConfirmExitJPanel.
     */
    public ConfirmExitJPanel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {// GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        JPanel jPanel1 = new JPanel();
        JLabel jLabel1 = new JLabel();
        JPanel jPanel2 = new JPanel();
        JButton confirmExit = new JButton();
        closeJButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        setPreferredSize(new java.awt.Dimension(240, 140));
        jLabel1.setText("Are you sure you want to Exit?");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel1);

        add(jPanel1, new java.awt.GridBagConstraints());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        confirmExit.setText("Exit");
        confirmExit.setContentAreaFilled(false);
        confirmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmExitActionPerformed(evt);
            }
        });

        jPanel2.add(confirmExit, new java.awt.GridBagConstraints());

        closeJButton.setText("Cancel");
        jPanel2.add(closeJButton, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        add(jPanel2, gridBagConstraints);

    }// GEN-END:initComponents

    private void confirmExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_confirmExitActionPerformed
        System.exit(0);
    }// GEN-LAST:event_confirmExitActionPerformed

    public void setup(ModelRoot mr, RenderersRoot vl, Action closeAction) {
        closeJButton.setAction(closeAction);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeJButton;

    // End of variables declaration//GEN-END:variables

}
