/*
 * FreeRails
 * Copyright (C) 2000-2018 The FreeRails Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * SaveGameJPanel.java
 *
 * Created on 30 August 2005, 22:53
 */

package freerails.client.view;

import freerails.client.renderer.RenderersRoot;
import freerails.controller.MessageToServer;
import freerails.controller.ModelRoot;
import freerails.controller.ModelRoot.Property;
import freerails.network.SaveGameMessageToServer;

import javax.swing.*;
import java.awt.event.ActionListener;

/**
 */
public class SaveGameJPanel extends javax.swing.JPanel implements View {

    private static final long serialVersionUID = 4031907071040752589L;
    ModelRoot modelRoot;
    ActionListener close;

    // </editor-fold>                        
    // Variables declaration - do not modify                     
    javax.swing.JButton cancelButton;
    javax.swing.JTextField fileNameTextField;
    javax.swing.JLabel jLabel1;
    javax.swing.JButton oKButton;

    /**
     * Creates new form SaveGameJPanel
     */
    public SaveGameJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code
    // ">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        fileNameTextField = new javax.swing.JTextField();
        oKButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Please enter a name for the save game.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(jLabel1, gridBagConstraints);

        fileNameTextField.setText("savegame");
        fileNameTextField
                .addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        fileNameTextFieldActionPerformed(evt);
                    }
                });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(fileNameTextField, gridBagConstraints);

        oKButton.setText("OK");
        oKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oKButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(oKButton, gridBagConstraints);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        add(cancelButton, gridBagConstraints);

    }

    private void oKButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_oKButtonActionPerformed

        String filename = fileNameTextField.getText();
        // Save the current game using the string
        modelRoot.setProperty(Property.QUICK_MESSAGE, "Saved game " + filename);
        MessageToServer message2 = new SaveGameMessageToServer(1, filename
                + ".sav");

        modelRoot.sendCommand(message2);
        close.actionPerformed(evt);
    }// GEN-LAST:event_oKButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
        close.actionPerformed(evt);
    }// GEN-LAST:event_cancelButtonActionPerformed

    private void fileNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fileNameTextFieldActionPerformed
        // TODO add your handling code here:
        System.out.println("fileNameTextFieldActionPerformed" + evt.toString());
    }// GEN-LAST:event_fileNameTextFieldActionPerformed

    /**
     * @param m
     * @param vl
     * @param closeAction
     */
    public void setup(ModelRoot m, RenderersRoot vl, Action closeAction) {
        this.close = closeAction;
        this.modelRoot = m;
    }
    // End of variables declaration                   

}
