/*
 * BuildJPane.java
 *
 * Created on 19 August 2003, 19:52
 */

package jfreerails.client.view;

import java.awt.GridBagConstraints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JPanel;

import jfreerails.client.common.ModelRoot;
import jfreerails.client.renderer.ViewLists;

/**
 * Displays the "Build" Tab.
 * @author  bob
 */
public class BuildJPane extends javax.swing.JPanel {
    
    private ActionRoot actionRoot;
    private JPanel currentPanel;
    private ModelRoot modelRoot;
    private ViewLists vl;
    
    public void validate() {
        super.validate();
        
    }
    
    
    public BuildJPane() {
        initComponents();
        setupComponents();
    }
    
    public void setup(ActionRoot actionRoot, ViewLists vl, ModelRoot modelRoot) {
        this.modelRoot = modelRoot;
        this.actionRoot = actionRoot;
        this.vl = vl;
        setBuildPanel("Track");
    }
    
    private void setupComponents() {
        /*
         * setup the "Build" combobox
         */
        buildCB.addItem("Track");
        buildCB.addItem("Station");
        buildCB.addActionListener(comboBoxActionListener);
    }
    
    private final ActionListener comboBoxActionListener = new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            String s = (String) buildCB.getSelectedItem();
            setBuildPanel(s);
        }
    };
    
    private void setBuildPanel(String s) {
        /* TODO */
        if (currentPanel != null) {
            remove(currentPanel);
        }
        if (s.equals("Track")) {
            currentPanel = new TrackBuildJPanel();
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.fill = GridBagConstraints.BOTH;
            gbc.weightx = gbc.weighty = 1.0;
            
            add(currentPanel, gbc);
            ((TrackBuildJPanel) currentPanel).setup(vl, actionRoot);
            revalidate();
            actionRoot.getStationBuildModel().getStationCancelAction().actionPerformed(new ActionEvent(
                    this,
                    ActionEvent.ACTION_PERFORMED, ""));
        } else if (s.equals("Station")) {
            currentPanel = new StationBuildJPanel();
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridx = 0;
            gbc.fill = GridBagConstraints.BOTH;
            gbc.weightx = gbc.weighty = 1.0;
            
            add(currentPanel, gbc);
            ((StationBuildJPanel) currentPanel).setup(actionRoot);
            revalidate();
        }
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buildCB = new javax.swing.JComboBox();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Build:");
        jPanel1.add(jLabel1);

        jPanel1.add(buildCB);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        add(jPanel1, gridBagConstraints);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox buildCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
