/*
 * TrainDialogueJPanel.java
 *
 * Created on 24 August 2003, 17:13
 */

package jfreerails.client.view;

import jfreerails.world.top.KEY;
import jfreerails.world.top.WorldListListener;

/**
 *
 * @author  Luke Lindsay
 */
public class TrainDialogueJPanel extends javax.swing.JPanel implements NewView, WorldListListener {
	
	
    
    /** Creates new form TrainDialogueJPanel */
    public TrainDialogueJPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        newTrainScheduleJPanel1 = new jfreerails.client.view.NewTrainScheduleJPanel();
        trainDetailsJPanel1 = new jfreerails.client.view.TrainDetailsJPanel();

        setLayout(new java.awt.BorderLayout());

        add(newTrainScheduleJPanel1, java.awt.BorderLayout.SOUTH);

        add(trainDetailsJPanel1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    public void setup(jfreerails.world.top.ReadOnlyWorld w, jfreerails.client.renderer.ViewLists vl, CallBacks cb) {
        newTrainScheduleJPanel1.setup(w, vl, cb);
        trainDetailsJPanel1.setup(w, vl, null);
             
    }    
    
    public void display(int trainNumber){
        newTrainScheduleJPanel1.display(trainNumber);
        trainDetailsJPanel1.displayTrain(trainNumber);
    }
    
    public void listUpdated(KEY key, int index) {
        newTrainScheduleJPanel1.listUpdated(key, index);
        trainDetailsJPanel1.listUpdated(key, index);
    }
    
    public void itemAdded(KEY key, int index) {
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jfreerails.client.view.NewTrainScheduleJPanel newTrainScheduleJPanel1;
    private jfreerails.client.view.TrainDetailsJPanel trainDetailsJPanel1;
    // End of variables declaration//GEN-END:variables
    
}
