/*
 * Copyright (C) Luke Lindsay
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

/*
 * File:           Track_TilesParsletImpl.java
 * Date:           21 January 2002  18:00
 *
 * @author  lindsal
 * @version generated by FFJ XML module
 */
package org.railz.server.parser;

import org.xml.sax.SAXException;


final public class Track_TilesParsletImpl implements Track_TilesParslet {
    public int template(final java.lang.String data) throws SAXException {
        try {
            return Integer.parseInt(data.trim());
        } catch (IllegalArgumentException ex) {
            throw new SAXException("template(" + data.trim() + ")", ex);
        }
    }

    public int[][] routesList(final java.lang.String data)
        throws SAXException {
        throw new SAXException("Not implemented yet.");
    }

    public int[] templatesList(final java.lang.String data)
        throws SAXException {
        throw new SAXException("Not implemented yet.");
    }
}
