/*
 * File:           Track_TilesParslet.java
 * Date:           21 January 2002  18:00
 *
 * @author  lindsal
 * @version generated by FFJ XML module
 */
package jfreerails.server.parser;

public interface Track_TilesParslet {
    int template(final java.lang.String data) throws org.xml.sax.SAXException;

    int[][] routesList(final java.lang.String data)
        throws org.xml.sax.SAXException;

    int[] templatesList(final java.lang.String data)
        throws org.xml.sax.SAXException;
}