/*
 * JPanel.java
 *
 * Created on 20 December 2003, 15:16
 */

package jfreerails.launcher;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import jfreerails.client.view.ServerControlModel;
import jfreerails.network.NewGameServerCommand;


/**
 * The Launcher panel that lets you load a game or start a new game with a choice
 * of maps.
 * @author rtuck99@users.sourceforge.net
 */
class MapSelectionPanel extends javax.swing.JPanel implements LauncherPanel {
    private static final String SELECT_A_MAP = "Select a map.";
    private static final String INVALID_PORT = "A valid port value is between between 0 and 65535.";
    private final LauncherInterface owner;
    
    private static final int LOAD_SAVED_GAME = 0;
    static final int START_NEW_MAP = 1;
    
    int getMapAction() {
        if (loadMapButton.isSelected()) {
            return LOAD_SAVED_GAME;
        }
		return START_NEW_MAP;
    }
    
    void setServerPortPanelVisible(boolean b){
        this.jPanel3.setVisible(b);
    }
    
    public String getMapName() {
        return (String) mapsJList.getSelectedValue();
    }
    
    
    MapSelectionPanel(LauncherInterface owner) {
        this.owner = owner;
        
        initComponents();
        
        /* initialise the map list */
        mapsJList.setListData(NewGameServerCommand.getMapNames());
        mapsJList.setSelectedIndex(0);
        
        owner.setNextEnabled(true);
        this.loadMapButton.setEnabled(ServerControlModel.isSaveGameAvailable());
        
        //Listen for changes in the server port text box.
        serverPort.getDocument().addDocumentListener(new DocumentListener(){
            public void insertUpdate(DocumentEvent e) {
                validateInput();
            }
            public void removeUpdate(DocumentEvent e) {
                validateInput();
            }
            public void changedUpdate(DocumentEvent e) {
                validateInput();
            }
            
        });
    }
    
    public boolean validateInput(){
        /* Validate map selection.*/
        if(newMapButton.isSelected() && mapsJList.getSelectedIndex() == -1){
            owner.setInfoText(SELECT_A_MAP, LauncherInterface.ERROR);
            return false;
        }
        
        /* Validate port.*/
        try{
            int port = getServerPort();
            if(port < 0 || port > 65535){
                owner.setInfoText(INVALID_PORT, LauncherInterface.ERROR);
                return false;
            }
        }catch(Exception e){
            owner.setInfoText(INVALID_PORT, LauncherInterface.ERROR);
            return false;
        }
        
        /*Everything is ok.*/
        owner.hideErrorMessages();
        return true;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        loadMapButton = new javax.swing.JRadioButton();
        newMapButton = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mapsJList = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        serverPort = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        buttonGroup1.add(loadMapButton);
        loadMapButton.setText("Load a saved game");
        jPanel2.add(loadMapButton);

        buttonGroup1.add(newMapButton);
        newMapButton.setSelected(true);
        newMapButton.setText("Start a new map");
        newMapButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                newMapButtonStateChanged(evt);
            }
        });

        jPanel2.add(newMapButton);

        add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "Select Map"));
        jScrollPane1.setViewportBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        mapsJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        mapsJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                mapsJListValueChanged(evt);
            }
        });

        jScrollPane1.setViewportView(mapsJList);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel3.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "Server port"));
        jLabel3.setText("Port:");
        jPanel3.add(jLabel3);

        serverPort.setColumns(6);
        serverPort.setText("55000");
        serverPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverPortActionPerformed(evt);
            }
        });
        serverPort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serverPortKeyReleased(evt);
            }
        });

        jPanel3.add(serverPort);

        add(jPanel3, java.awt.BorderLayout.SOUTH);

    }//GEN-END:initComponents
    
    private void mapsJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_mapsJListValueChanged
        // TODO add your handling code here:
        validateInput();
    }//GEN-LAST:event_mapsJListValueChanged
    
    private void serverPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverPortActionPerformed
        
    }//GEN-LAST:event_serverPortActionPerformed
    
    private void serverPortKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serverPortKeyReleased
        
    }//GEN-LAST:event_serverPortKeyReleased
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        owner.setNextEnabled(true);
    }//GEN-LAST:event_formComponentShown
    
    private void newMapButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_newMapButtonStateChanged
        mapsJList.setEnabled(newMapButton.isSelected());
        validateInput();
    }//GEN-LAST:event_newMapButtonStateChanged
    
    int getServerPort() {
        String s = serverPort.getText();
        return Integer.parseInt(s);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.ButtonGroup buttonGroup1;
    javax.swing.JLabel jLabel3;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel3;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JRadioButton loadMapButton;
    javax.swing.JList mapsJList;
    javax.swing.JRadioButton newMapButton;
    javax.swing.JTextField serverPort;
    // End of variables declaration//GEN-END:variables
    
}
