/*
 * JPanel.java
 *
 * Created on 20 December 2003, 15:16
 */

package jfreerails.launcher;

import jfreerails.server.GameServer;

/**
 *
 * @author rtuck99@users.sourceforge.net
 */
class MapSelectionPanel extends javax.swing.JPanel {
    private Launcher owner;

    static final int LOAD_SAVED_GAME = 0;
    static final int START_NEW_MAP = 1;

    int getMapAction() {
	if (loadMapButton.isSelected()) {
	    return LOAD_SAVED_GAME;
	} else {
	    return START_NEW_MAP;
	}
    }
    
    public String getMapName() {
	return (String) jList1.getSelectedValue();
    }

    /** Creates new form JPanel */
    MapSelectionPanel(Launcher owner) {
	this.owner = owner;

        initComponents();

	/* initialise the map list */
	jList1.setListData(GameServer.getMapNames());
	jList1.setSelectedIndex(0);

	owner.setNextEnabled(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        loadMapButton = new javax.swing.JRadioButton();
        newMapButton = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        loadMapButton.setText(jfreerails.util.Resources.get("Load a saved game"));
        buttonGroup1.add(loadMapButton);
        jPanel2.add(loadMapButton);

        newMapButton.setSelected(true);
        newMapButton.setText(jfreerails.util.Resources.get("Start a new map"));
        buttonGroup1.add(newMapButton);
        newMapButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                newMapButtonStateChanged(evt);
            }
        });

        jPanel2.add(newMapButton);

        add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), jfreerails.util.Resources.get("Select Map")));
        jScrollPane1.setViewportBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
	owner.setNextEnabled(true);
    }//GEN-LAST:event_formComponentShown

    private void newMapButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_newMapButtonStateChanged
	jList1.setEnabled(newMapButton.isSelected());
    }//GEN-LAST:event_newMapButtonStateChanged
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton loadMapButton;
    private javax.swing.JRadioButton newMapButton;
    // End of variables declaration//GEN-END:variables
    
}
