/*
 * ServerStatusPanel.java
 *
 * Created on 20 December 2003, 23:06
 */

package jfreerails.launcher;

import javax.swing.table.TableModel;

/**
 *
 * @author  rtuck99@users.sourceforge.net
 */
class ServerStatusPanel extends javax.swing.JPanel {
    private Launcher owner;

    /** Creates new form ServerStatusPanel */
    ServerStatusPanel(Launcher owner) {
	this.owner = owner;
        initComponents();
	owner.setNextEnabled(true);
    }
    
    void setTableModel(TableModel tm) {
	jTable1.setModel(tm);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), jfreerails.util.Resources.get("Server Status")));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jScrollPane1.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTable1.setPreferredScrollableViewportSize(new java.awt.Dimension(450, 88));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
	owner.setNextEnabled(true);
    }//GEN-LAST:event_formComponentShown
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
