/*
 * Copyright (C) 2003 Robert Tuck
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

/*
 * ClientOptionsJPanel.java
 *
 * Created on 20 December 2003, 15:57
 */

package org.railz.launcher;

import java.awt.DisplayMode;

import org.railz.client.view.MyDisplayMode;
import org.railz.util.Resources;

/**
 *
 * @author  rtuck99@users.sourceforge.net
 */
class ClientOptionsJPanel extends javax.swing.JPanel {
    private Launcher owner;
    
    String getPlayerName() {
	return playerName.getText();
    }

    DisplayMode getDisplayMode() {
	MyDisplayMode mdm = (MyDisplayMode) listModel.getElementAt
		(jList1.getSelectedIndex());
	return mdm == null ? null : mdm.displayMode;
    }

    boolean isWindowed() {
	return windowedButton.isSelected();
    }

    public void setControlsEnabled(boolean enabled) {
	windowedButton.setEnabled(enabled);
	fullScreenButton.setEnabled(enabled);
	if (fullScreenButton.isSelected()) {
	    jList1.setEnabled(enabled);
	}
    }
    
    private void validateSettings() {
	boolean isValid = false;
	String infoText = "";
	if (playerName.getText() == null ||
	    playerName.getText().equals("")) {
	    infoText = Resources.get("Please set a name for your player");
	} else {
	    isValid = true;
	}
	owner.setInfoText(infoText);
	owner.setNextEnabled(isValid);
    }

    private DisplayModeListModel listModel;

    /** Creates new form ClientOptionsJPanel */
    public ClientOptionsJPanel(Launcher owner) {
	this.owner = owner;
        initComponents();
	listModel = new DisplayModeListModel();
	jList1.setModel(listModel);
	jList1.setSelectedIndex(0);
	validateSettings();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        playerName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        windowedButton = new javax.swing.JRadioButton();
        fullScreenButton = new javax.swing.JRadioButton();

        setLayout(new java.awt.BorderLayout());

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel3.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), org.railz.util.Resources.get("Player Details")));
        jLabel1.setText(org.railz.util.Resources.get("Player name:"));
        jPanel3.add(jLabel1);

        playerName.setColumns(12);
        playerName.setText(org.railz.util.Resources.get("Player1"));
        playerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerNameActionPerformed(evt);
            }
        });
        playerName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                playerNameFocusLost(evt);
            }
        });

        jPanel3.add(playerName);

        add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), org.railz.util.Resources.get("Select Display Mode")));
        jScrollPane1.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setEnabled(false);
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        windowedButton.setSelected(true);
        windowedButton.setText(org.railz.util.Resources.get("Windowed"));
        buttonGroup1.add(windowedButton);
        jPanel2.add(windowedButton);

        fullScreenButton.setText(org.railz.util.Resources.get("Full screen"));
        buttonGroup1.add(fullScreenButton);
        fullScreenButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fullScreenButtonStateChanged(evt);
            }
        });

        jPanel2.add(fullScreenButton);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
	validateSettings();
    }//GEN-LAST:event_formComponentShown

    private void playerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerNameActionPerformed
	validateSettings();
    }//GEN-LAST:event_playerNameActionPerformed

    private void playerNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_playerNameFocusLost
	validateSettings();
    }//GEN-LAST:event_playerNameFocusLost

    private void fullScreenButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fullScreenButtonStateChanged
	jList1.setEnabled(fullScreenButton.isSelected());
    }//GEN-LAST:event_fullScreenButtonStateChanged
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton fullScreenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField playerName;
    private javax.swing.JRadioButton windowedButton;
    // End of variables declaration//GEN-END:variables
    
}
