package experimental;

import java.awt.Dimension;
import java.io.IOException;
import java.util.Random;

import javax.swing.JComponent;

import jfreerails.client.common.JFrameMinimumSizeEnforcer;
import jfreerails.client.common.MyGlassPanel;
import jfreerails.client.renderer.ViewLists;
import jfreerails.client.top.ViewListsImpl;
import jfreerails.client.view.DialogueBoxController;
import jfreerails.client.view.MapCursor;
import jfreerails.client.view.TrainViewJList;
import jfreerails.controller.MoveChainFork;
import jfreerails.server.NewTileSetFactoryImpl;
import jfreerails.server.TileSetFactory;
import jfreerails.server.WagonAndEngineTypesFactory;
import jfreerails.world.cargo.CargoBatch;
import jfreerails.world.cargo.CargoBundle;
import jfreerails.world.cargo.CargoBundleImpl;
import jfreerails.world.station.StationModel;
import jfreerails.world.top.KEY;
import jfreerails.world.top.World;
import jfreerails.world.top.WorldImpl;
import jfreerails.world.train.Schedule;
import jfreerails.world.train.TrainModel;
import jfreerails.world.train.TrainOrdersModel;
/**
 * This class lets you test dialogue boxes without running the whole game. 
 * @author  lindsal8
 *
 */
public class DialogueBoxTester extends javax.swing.JFrame {

	private final DialogueBoxController dialogueBoxController;

	private Random randy = new Random(System.currentTimeMillis());

	private World w;

	private ViewLists vl;

	/** Creates new form TestGlassPanelMethod */
	public DialogueBoxTester() {

		dialogueBoxController = new DialogueBoxController(this);
		w = new WorldImpl();
		WagonAndEngineTypesFactory wetf = new WagonAndEngineTypesFactory();
		TileSetFactory tileFactory = new NewTileSetFactoryImpl();
		tileFactory.addTerrainTileTypesList(w);
		wetf.addTypesToWorld(w);
		int numberOfCargoTypes = w.size(KEY.CARGO_TYPES);

		w.add(
			KEY.STATIONS,
			new StationModel(10, 10, "Bristol", numberOfCargoTypes, 0));
		w.add(
			KEY.STATIONS,
			new StationModel(10, 10, "Bath", numberOfCargoTypes, 0));
		w.add(
			KEY.STATIONS,
			new StationModel(10, 10, "Cardiff", numberOfCargoTypes, 0));
		w.add(
			KEY.STATIONS,
			new StationModel(10, 10, "London", numberOfCargoTypes, 0));
		w.add(
			KEY.STATIONS,
			new StationModel(10, 10, "Swansea", numberOfCargoTypes, 0));
		//Set up cargo bundle, for the purpose of this test code all the trains can share the
		//same one.
		CargoBundle cb = new CargoBundleImpl();
		cb.setAmount(new CargoBatch(0, 10, 10, 8, 0), 10);
		cb.setAmount(new CargoBatch(0, 10, 10, 9, 0), 10);
		cb.setAmount(new CargoBatch(1, 10, 10, 9, 0), 10);
		cb.setAmount(new CargoBatch(3, 10, 10, 9, 0), 10);
		cb.setAmount(new CargoBatch(5, 10, 10, 9, 0), 10);
		w.add(KEY.CARGO_BUNDLES, cb);

		Schedule schedule = new Schedule();
		TrainOrdersModel order =
			new TrainOrdersModel(0, new int[] { 0, 0, 0 }, false);
		schedule.setOrder(0, order);
		schedule.setOrder(1, order);
		schedule.setOrder(2, order);
		schedule.setOrder(3, order);
		schedule.setOrder(4, order);
	
		w.add(KEY.TRAINS, new TrainModel(0, new int[] { 0, 0 }, null, schedule));

		w.add(KEY.TRAINS, new TrainModel(1, new int[] { 1, 1 }, null, schedule));

		w.add(KEY.TRAINS, new TrainModel(0, new int[] { 1, 2, 0 }, null, schedule));

		try {
			vl = new ViewListsImpl(w); //new ViewListsImpl();

			final MyGlassPanel glassPanel = new MyGlassPanel();
			dialogueBoxController.setup(
				w,
				vl,
				new MoveChainFork(),
				MapCursor.NULL_MAP_CURSOR);
			initComponents();

			glassPanel.setSize(800, 600);
			//this.setGlassPane(glassPanel);
			this.addComponentListener(new JFrameMinimumSizeEnforcer(640, 400));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		//pack();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the FormEditor.
	 */
	private void initComponents() { //GEN-BEGIN:initComponents
		jLabel1 = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		show = new javax.swing.JMenu();
		newspaper = new javax.swing.JMenuItem();
		selectEngine = new javax.swing.JMenuItem();
		selectWagons = new javax.swing.JMenuItem();
		selectTrainOrders = new javax.swing.JMenuItem();
		showControls = new javax.swing.JMenuItem();
		showTerrainInfo = new javax.swing.JMenuItem();
		showStationInfo = new javax.swing.JMenuItem();
		showTrainConsist = new javax.swing.JMenuItem();
		showTrainList = new javax.swing.JMenuItem();

		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				exitForm(evt);
			}
		});

		jLabel1.setIcon(
			new javax.swing.ImageIcon(
				getClass().getResource("/jfreerails/data/south_america.png")));
		getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

		show.setText("Show");
		newspaper.setText("Newspaper");
		newspaper.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				newspaperActionPerformed(evt);
			}
		});

		show.add(newspaper);

		selectEngine.setText("Select Engine");
		selectEngine.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				selectEngineActionPerformed(evt);
			}
		});

		show.add(selectEngine);

		selectWagons.setText("Select Wagons");
		selectWagons.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				selectWagonsActionPerformed(evt);
			}
		});

		show.add(selectWagons);

		selectTrainOrders.setText("Train Orders");
		selectTrainOrders
			.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				selectTrainOrdersActionPerformed(evt);
			}
		});

		show.add(selectTrainOrders);

		showControls.setText("Show game controls");
		showControls.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				showControlsActionPerformed(evt);
			}
		});

		show.add(showControls);

		showTerrainInfo.setText("Show Terrain Info");
		showTerrainInfo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				showTerrainInfoActionPerformed(evt);
			}
		});

		show.add(showTerrainInfo);

		showStationInfo.setText("Show Station Info");
		showStationInfo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				showStationInfoActionPerformed(evt);
			}
		});

		show.add(showStationInfo);

		showTrainConsist.setText("Train Consist");
		showTrainConsist
			.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				showTrainConsistActionPerformed(evt);
			}
		});

		show.add(showTrainConsist);

		showTrainList.setText("Item");
		showTrainList.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				showTrainListActionPerformed(evt);
			}
		});

		show.add(showTrainList);

		jMenuBar1.add(show);

		setJMenuBar(jMenuBar1);

	} //GEN-END:initComponents

	private void showTrainListActionPerformed(
		java.awt.event.ActionEvent evt) {
		//GEN-FIRST:event_showTrainListActionPerformed		
		dialogueBoxController. showTrainList();
	} //GEN-LAST:event_showTrainListActionPerformed

	private void showTrainConsistActionPerformed(
		java.awt.event.ActionEvent evt) {
		//GEN-FIRST:event_showTrainConsistActionPerformed
		// Add your handling code here:
		//TrainView
		int trainNumber = randy.nextInt(w.size(KEY.TRAINS) - 1);
		JComponent trainView = new TrainViewJList(w, vl, trainNumber);
		dialogueBoxController.showContent(trainView);
	} //GEN-LAST:event_showTrainConsistActionPerformed

	private void showStationInfoActionPerformed(
		java.awt.event.ActionEvent evt) {
		//GEN-FIRST:event_showStationInfoActionPerformed
		// Add your handling code here:
		int stationNumber = randy.nextInt(w.size(KEY.STATIONS) - 1);
		dialogueBoxController.showStationInfo(stationNumber);
	} //GEN-LAST:event_showStationInfoActionPerformed

	private void showTerrainInfoActionPerformed(
		java.awt.event.ActionEvent evt) {
		//GEN-FIRST:event_showTerrainInfoActionPerformed
		// Add your handling code here:
		int terrainType = randy.nextInt(w.size(KEY.TERRAIN_TYPES) - 1);
		dialogueBoxController.showTerrainInfo(terrainType);
	} //GEN-LAST:event_showTerrainInfoActionPerformed

	private void showControlsActionPerformed(
		java.awt.event.ActionEvent evt) {
		//GEN-FIRST:event_showControlsActionPerformed
		// Add your handling code here:
		dialogueBoxController.showGameControls();
	} //GEN-LAST:event_showControlsActionPerformed

	private void selectTrainOrdersActionPerformed(
		java.awt.event.ActionEvent evt) {
		//GEN-FIRST:event_selectTrainOrdersActionPerformed
		// Add your handling code here:
		dialogueBoxController.showTrainOrders();
	} //GEN-LAST:event_selectTrainOrdersActionPerformed

	private void selectWagonsActionPerformed(
		java.awt.event.ActionEvent evt) {
		//GEN-FIRST:event_selectWagonsActionPerformed
		// Add your handling code here:
		dialogueBoxController.showSelectWagons();
	} //GEN-LAST:event_selectWagonsActionPerformed

	private void selectEngineActionPerformed(
		java.awt.event.ActionEvent evt) {
		//GEN-FIRST:event_selectEngineActionPerformed
		// Add your handling code here:
		dialogueBoxController.showSelectEngine();
	} //GEN-LAST:event_selectEngineActionPerformed

	private void newspaperActionPerformed(
		java.awt.event.ActionEvent evt) {
		//GEN-FIRST:event_newspaperActionPerformed
		// Add your handling code here:
		dialogueBoxController.showNewspaper("New headline!");
	} //GEN-LAST:event_newspaperActionPerformed

	/** Exit the Application */
	private void exitForm(
		java.awt.event.WindowEvent evt) { //GEN-FIRST:event_exitForm
		System.exit(0);
	} //GEN-LAST:event_exitForm

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		DialogueBoxTester test = new DialogueBoxTester();

		test.setSize(new Dimension(640, 400));
		test.show();
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem newspaper;
	private javax.swing.JMenuItem selectEngine;
	private javax.swing.JMenuItem selectTrainOrders;
	private javax.swing.JMenuItem selectWagons;
	private javax.swing.JMenu show;
	private javax.swing.JMenuItem showControls;
	private javax.swing.JMenuItem showStationInfo;
	private javax.swing.JMenuItem showTerrainInfo;
	private javax.swing.JMenuItem showTrainConsist;
	private javax.swing.JMenuItem showTrainList;
	// End of variables declaration//GEN-END:variables

}
